
OTP_PURPOSE_ACCOUNT_VERIFICATION: str = "account_verification"
OTP_PURPOSE_FORGOT_PASSWORD: str = "forgot_password"
OTP_EXPIRY_IN_MINUTES: int = 5
OTP_COOL_DOWN_IN_MINUTES: int = 2


RATE_LIMIT_SCOPE_KEY_REGISTRATION = "registration"
RATE_LIMIT_SCOPE_KEY_LOGIN = "login"
RATE_LIMIT_SCOPE_KEY_OTP_ACCOUNT_VERIFICATION = "verify_account"
RATE_LIMIT_SCOPE_KEY_OTP_FORGOT_PASSWORD = "forgot_password"
RATE_LIMIT_SCOPE_KEY_RESEND_OTP = "resend_otp"
