"""added calm down time

Revision ID: 71ba9a5e4802
Revises: 821f91f6cef7
Create Date: 2026-02-27 19:09:37.379867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ba9a5e4802'
down_revision: Union[str, Sequence[str], None] = '821f91f6cef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verification', sa.Column('resend_available_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verification', 'resend_available_at')
    # ### end Alembic commands ###
