"""test

Revision ID: 9dec70342894
Revises: f510db312925
Create Date: 2026-02-20 00:30:13.717032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dec70342894'
down_revision: Union[str, Sequence[str], None] = 'f510db312925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verification', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_column('otp_verification', 'uid')
    op.drop_column('refresh_tokens', 'parent_token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('parent_token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('otp_verification', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('otp_verification', 'id')
    # ### end Alembic commands ###
